name: Versioning

on:
  push:
      branches:
            - main

permissions: write-all
jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 18"
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Print Changed Files
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git diff --name-only HEAD FETCH_HEAD
      continue-on-error: true

    - name: Get Changed Files
      id: changed-files
      run: |
        # Get the list of changed files and store it as a space-separated string
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "::set-output name=changedFiles::$CHANGED_FILES"

    - name: Set Scope for Lerna Versioning
      run: |
        node set-scope.js ${{ steps.changed-files.outputs.changedFiles }}

    - name: Commit changes
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add lerna.json
        git commit -m "chore: Committing changes in lerna.json"
        git checkout -- package-lock.json

    - name: Print Changed Files
      run: |
        npx lerna init --independent
        
    - name: "Version and publish" 
      env:
        GH_TOKEN: ${{ secrets.PAT_GITHUB2 }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        npx lerna publish --yes --skip-npm

